service: php-service # NOTE: update this with your service name
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: provided
  stage: dev
  region: ap-northeast-2

custom: ${file(vpc.json)}

functions:
  hello:
    handler: index.php 
    vpc:
      securityGroupIds: 
        - ${self:custom.security_group.value} 
      subnetIds:
        - ${self:custom.subnet_private_1.value} 
        - ${self:custom.subnet_private_2.value} 
    layers:
      - arn:aws:lambda:ap-northeast-2:887080169480:layer:php71:5

    events:
      - http:
          path: /{proxy+} 
          method: ANY 
